# Site settings
title: Joël SAGNON - Agile catalyst & coach
description: A blog about Agile
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jsagnon.github.io"

# User settings
username: Joel SAGNON
user_description: Agile Catalyst @HardisGroup
email: joel.sagnon@gmail.com
twitter_username: JoelSAGNON
github_username:  jsagnon
gplus_username:  JoelSagnonS
disqus_username: jsagnon

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
# compress_html: true
#   clippings: all
#   comments: all
#   endings: []
#   profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Vidéos
    url: /videos
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']